# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  - package-ecosystem: "attr" # See documentation for possible values
    directory: "/" # Location of package manifests
    schedule:
      interval: "weekly"
      
  - package-ecosystem: "inflect" # See documentation for possible values
    directory: "/" # Location of package manifests
    schedule:
      interval: "weekly"
      
  - package-ecosystem: "lmfit" # See documentation for possible values
    directory: "/" # Location of package manifests
    schedule:
      interval: "weekly"
      
  - package-ecosystem: "matplotlib" # See documentation for possible values
    directory: "/" # Location of package manifests
    schedule:
      interval: "weekly"
      
  - package-ecosystem: "numpy" # See documentation for possible values
    directory: "/" # Location of package manifests
    schedule:
      interval: "weekly"
      
  - package-ecosystem: "pandas" # See documentation for possible values
    directory: "/" # Location of package manifests
    schedule:
      interval: "weekly"

  - package-ecosystem: "pytest" # See documentation for possible values
    directory: "/" # Location of package manifests
    schedule:
      interval: "weekly"

  - package-ecosystem: "scipy" # See documentation for possible values
    directory: "/" # Location of package manifests
    schedule:
      interval: "weekly"

  - package-ecosystem: "sympy" # See documentation for possible values
    directory: "/" # Location of package manifests
    schedule:
      interval: "weekly"

  - package-ecosystem: "scikit" # See documentation for possible values
    directory: "/" # Location of package manifests
    schedule:
      interval: "weekly"

  - package-ecosystem: "uncertainties" # See documentation for possible values
    directory: "/" # Location of package manifests
    schedule:
      interval: "weekly"
